/// Flutter icons WCustomIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  WCustomIcons
///      fonts:
///       - asset: fonts/WCustomIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class WCustomIcons {
  WCustomIcons._();

  static const _kFontFam = 'WCustomIcons';
  static const _kFontPkg = null;

  static const IconData receipt = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData table = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData exit = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData piggy = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData condensed = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData expanded = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menu = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData food = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cancelled_receipt = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sort = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
